google_maps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls', namespace="main")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
	
	path('', views.route, name="route"),
	path('map', views.map, name="map"),

	]

main/models.py
from django.db import models

main/views.py
from django.shortcuts import render
from django.conf import settings

from .mixins import Directions
'''
Basic view for routing 
'''
def route(request):

	context = {"google_api_key": settings.GOOGLE_API_KEY}
	return render(request, 'main/route.html', context)


'''
Basic view for displaying a map 
'''
def map(request):

	lat_a = request.GET.get("lat_a")
	long_a = request.GET.get("long_a")
	lat_b = request.GET.get("lat_b")
	long_b = request.GET.get("long_b")
	directions = Directions(
		lat_a= lat_a,
		long_a=long_a,
		lat_b = lat_b,
		long_b=long_b
		)

	context = {
	"google_api_key": settings.GOOGLE_API_KEY,
	"lat_a": lat_a,
	"long_a": long_a,
	"lat_b": lat_b,
	"long_b": long_b,
	"origin": f'{lat_a}, {long_a}',
	"destination": f'{lat_b}, {long_b}',
	"directions": directions,

	}
	return render(request, 'main/map.html', context)

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main.css' %}"></link>

  <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->
  {% block extend_head %}

  {% endblock %}

</head>
<body>

  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% block extend_nav %}

  {% endblock %}

  <div class="div-container">
    
    {% include 'main/partials/logo.html' %}

    {% block content %}

    {% endblock %}

  </div>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
  {% block extend_footer %}

  {% endblock %}

  <script src="{% static 'main.js' %}"></script>
  

</body>
</html>

main/templates/main/map.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>



{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li><a href="{% url 'main:route' %}">Demo Routing</a></li>
  <li><a class="active" href="#map">Demo Map</a></li>
</ul>

{% endblock %}


{% block content %}

<h3 id="map">Django Google Maps API Demo - Map</h3>

<div class="container">

  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Start</td>
        <td>{{directions.origin}}</td>      
      </tr>
      <tr>
        <td>Destination</td>
        <td>{{directions.destination}}</td>      
      </tr>
      <tr>
        <td>Duration</td>
        <td>{{directions.duration}}</td>      
      </tr>
      <tr>
        <td>Distance</td>
        <td>{{directions.distance}}</td>      
      </tr>
      <tr>
        <td>Directions</td>
        <td id="dir-toggle">click <a href="javascript:void(0)" onclick="DirectionsToggle()">here</a></td>      
      </tr>

    </tbody>
  </table>

  <table id="dir-table" hidden>
    <thead>
      <tr>
        <th>Directions</th>
        <th>Distance</th>
        <th>Duration</th>
      </tr>
    </thead>
    <tbody>
      {% for dist, dur, text in directions.steps %}
      <tr>
        <td>{{text|safe}}</td>
        <td>{{dist}}</td>
        <td>{{dur}}</td>   
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>

<div class="map-container">

   <div id="map-route"></div>


</div>

{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";
    var lat_a = {{lat_a|safe}};
    var long_a = {{long_a|safe}};
    var lat_b = {{lat_a|safe}};
    var long_b = {{long_b|safe}};
    var origin = "{{origin|safe}}";
    var destination = "{{destination|safe}}";
    var directions = {{directions|safe}}

  </script>

  <script src="{% static 'google_maps.js' %}"></script>


{% endblock %}

main/templates/main/partials/logo.html
{% load static %}
<a href="{% url 'main:route' %}">
	<div class="brand-logo">
		<img class="logo" src="{% static 'branding/did_logo.gif' %}" />
	</div>
</a>

main/templates/main/route.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>

{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li><a class="active" href="{% url 'main:route' %}">Demo Routing</a></li>
  <li><a href="javascript:void(0)" onclick="alert('Please add a start and end address')">Demo Map</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Google Maps API Demo - Routing</h3>

<div class="container">

   <label for="id-google-address-a">Start Address</label>
   <input type="text" placeholder="*Begin typing address" id="id-google-address-a" name="google_address_a">

   <label for="id-google-address-b">Destination Address</label>
   <input type="text" placeholder="*Begin typing address" id="id-google-address-b" name="google_address_b">


   <input type="hidden" class="geo" id="id-lat-a" value="">
   <input type="hidden" class="geo" id="id-long-a" value="">
   <input type="hidden" class="geo" id="id-lat-b" value="">
   <input type="hidden" class="geo" id="id-long-b" value="">


</div>

{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";

  </script>

  <script src="{% static 'google_places.js' %}"></script>


{% endblock %}